services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always

    networks:
      - autoescola-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    networks:
      - autoescola-network

  projeto-auto-escola-deploy:
    image: projeto-auto-escola-deploy
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo    
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - autoescola-network  
      
networks:
    autoescola-network:
        driver: bridge